# Generated by Django 4.2.2 on 2023-06-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminderitem',
            name='remind_date',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
