# Generated by Django 4.2.2 on 2023-07-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0003_alter_reminderitem_remind_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminderitem',
            name='reminder_on',
            field=models.BooleanField(default=0, verbose_name='Remind enable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reminderitem',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='reminderitem',
            name='remind_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Remind date'),
        ),
    ]
