# Generated by Django 4.2.2 on 2023-07-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0004_reminderitem_reminder_on_alter_reminderitem_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminderitem',
            name='remind_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Remind time'),
        ),
        migrations.AlterField(
            model_name='reminderitem',
            name='content',
            field=models.TextField(max_length=200, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='reminderitem',
            name='remind_date',
            field=models.DateField(blank=True, null=True, verbose_name='Remind date'),
        ),
    ]
