# Generated by Django 4.2.2 on 2023-07-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0005_reminderitem_remind_time_alter_reminderitem_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminderitem',
            name='title',
            field=models.CharField(default='Test title', max_length=50, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reminderitem',
            name='content',
            field=models.TextField(blank=True, max_length=200, verbose_name='Content'),
        ),
    ]
